"""odoo-boost uninstall – clean up generated agent files and optionally remove config."""

from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console

from odoo_boost.agents import AGENTS
from odoo_boost.cli.gitignore import ignore_entry, managed_entries, update_gitignore
from odoo_boost.config.settings import load_config

console = Console()


def uninstall(
    config: Annotated[
        Path | None, typer.Option("--config", "-c", help="Path to odoo-boost.json")
    ] = None,
    keep_config: Annotated[
        bool,
        typer.Option(
            "--keep-config",
            help="Keep odoo-boost.json and remove only generated agent files.",
        ),
    ] = False,
    yes: Annotated[
        bool,
        typer.Option(
            "--yes",
            "-y",
            help="Skip confirmation prompts and delete files.",
        ),
    ] = False,
    gitignore: Annotated[
        bool | None,
        typer.Option(
            "--gitignore/--no-gitignore", help="Remove managed entries for deleted files."
        ),
    ] = None,
) -> None:
    """Remove files generated by Odoo Boost for configured agents."""
    try:
        cfg = load_config(config)
    except FileNotFoundError:
        console.print("[red]No odoo-boost.json found.[/]")
        raise typer.Exit(1) from None

    project_path = Path(cfg.project_path).resolve() if cfg.project_path != "." else Path.cwd()

    if not yes:
        # Prompt if the user wants to keep agent files. Default is False (delete them).
        keep_files = typer.confirm(
            "Do you want to keep generated agent files (AGENTS.md, configs, skills)?",
            default=False,
        )
        if keep_files:
            console.print("[yellow]Aborted uninstall. Keeping all files.[/]")
            raise typer.Exit(0)

        if not keep_config:
            # Prompt if the user wants to keep the config file. Default is False (delete it).
            keep_cfg_prompt = typer.confirm(
                "Do you want to keep your configuration file (odoo-boost.json)?",
                default=False,
            )
            if keep_cfg_prompt:
                keep_config = True

    console.print("[bold]Uninstalling Odoo Boost files…[/]\n")

    removed_any = False
    removed_files: list[Path] = []
    for agent_id in cfg.agents:
        agent_cls = AGENTS.get(agent_id)
        if agent_cls is None:
            continue

        agent = agent_cls(config=cfg, project_path=project_path)
        removed_paths = agent.uninstall()
        for p in removed_paths or []:
            removed_files.append(p)
            try:
                rel = p.relative_to(project_path)
            except ValueError:
                rel = p
            console.print(f"  [red]Removed[/] {rel}")
            removed_any = True

    if not keep_config:
        cfg_file = config or (project_path / "odoo-boost.json")
        if cfg_file.is_file():
            cfg_file.unlink()
            removed_files.append(cfg_file)
            try:
                rel = cfg_file.relative_to(project_path)
            except ValueError:
                rel = cfg_file
            console.print(f"  [red]Removed[/] {rel}")
            removed_any = True

    managed = managed_entries(project_path)
    removable = {
        ignore_entry(project_path, path)
        for path in removed_files
        if path.absolute().is_relative_to(project_path.absolute())
    } & managed
    if removable:
        console.print("\n[bold]Managed .gitignore entries for removed files:[/]")
        for entry in sorted(removable):
            console.print(f"  {entry}", markup=False)
        if gitignore is True or (
            gitignore is None
            and not yes
            and typer.confirm("Remove these entries from .gitignore?", default=False)
        ):
            update_gitignore(project_path, remove=removable)
            console.print("  [green]Updated[/] .gitignore")

    if not removed_any:
        console.print("  [dim]No generated files found to remove.[/]")

    console.print("\n[green]Uninstall complete![/]")
