"""Tests for odoo_boost.guidelines.composer."""

from __future__ import annotations

from odoo_boost.guidelines.composer import _CORE_FILES, compose_guidelines


class TestComposeGuidelines:
    def test_includes_header(self):
        result = compose_guidelines()
        assert "# Odoo Development Guidelines" in result

    def test_includes_auto_generated_note(self):
        result = compose_guidelines()
        assert "Auto-generated by **Odoo Boost**" in result

    def test_includes_all_core_sections(self):
        result = compose_guidelines()
        # Each core file contributes content; check we have at least 9 sections
        # by verifying multiple known topic keywords
        for keyword in ["ORM", "security", "controller", "testing", "module"]:
            assert keyword.lower() in result.lower()

    def test_ends_with_newline(self):
        result = compose_guidelines()
        assert result.endswith("\n")

    def test_version_specific_addendum_v18(self):
        result = compose_guidelines(version="18.0")
        # Version 18 addendum should be appended (or silently skipped if file missing)
        assert isinstance(result, str)
        assert len(result) > 100

    def test_version_specific_addendum_v17(self):
        result = compose_guidelines(version="17.0")
        assert isinstance(result, str)
        assert len(result) > 100

    def test_unknown_version_no_crash(self):
        """A version without a specific file should not crash."""
        result = compose_guidelines(version="99.0")
        assert "# Odoo Development Guidelines" in result

    def test_no_version(self):
        result = compose_guidelines(version=None)
        assert "# Odoo Development Guidelines" in result

    def test_core_files_list_not_empty(self):
        assert len(_CORE_FILES) == 10
        assert "oca_standards.md" in _CORE_FILES

    def test_includes_oca_standards(self):
        result = compose_guidelines()
        assert "Odoo Community Association (OCA) Standards" in result
        assert "ir.model.access.csv" in result

    def test_version_specific_addenda(self):
        for ver in ["14.0", "15.0", "16.0", "17.0", "18.0", "19.0"]:
            result = compose_guidelines(version=ver)
            major = ver.split(".")[0]
            assert f"Odoo {major}" in result
