"""Tests for odoo_boost.guidelines.composer."""

from __future__ import annotations

from odoo_boost.guidelines.composer import (
    _CORE_FILES,
    compose_agent_guidelines,
    compose_guidelines,
    compose_guidelines_index,
    install_guideline_references,
)


class TestComposeGuidelines:
    def test_includes_header(self):
        result = compose_guidelines()
        assert "# Odoo Development Guidelines" in result

    def test_includes_auto_generated_note(self):
        result = compose_guidelines()
        assert "Auto-generated by **Odoo Boost**" in result

    def test_includes_all_core_sections(self):
        result = compose_guidelines()
        # Each core file contributes content; check we have at least 9 sections
        # by verifying multiple known topic keywords
        for keyword in ["ORM", "security", "controller", "testing", "module"]:
            assert keyword.lower() in result.lower()

    def test_ends_with_newline(self):
        result = compose_guidelines()
        assert result.endswith("\n")

    def test_version_specific_addendum_v18(self):
        result = compose_guidelines(version="18.0")
        # Version 18 addendum should be appended (or silently skipped if file missing)
        assert isinstance(result, str)
        assert len(result) > 100

    def test_version_specific_addendum_v17(self):
        result = compose_guidelines(version="17.0")
        assert isinstance(result, str)
        assert len(result) > 100

    def test_unknown_version_no_crash(self):
        """A version without a specific file should not crash."""
        result = compose_guidelines(version="99.0")
        assert "# Odoo Development Guidelines" in result

    def test_no_version(self):
        result = compose_guidelines(version=None)
        assert "# Odoo Development Guidelines" in result

    def test_core_files_list_not_empty(self):
        assert len(_CORE_FILES) == 11
        assert "operating_rules.md" in _CORE_FILES
        assert "oca_standards.md" in _CORE_FILES

    def test_includes_agent_operating_rules(self):
        result = compose_guidelines()
        assert "Agent Operating Rules" in result
        assert "Strict Prohibition on Live Environment Execution" in result
        assert "No Unsolicited Automated Tests" in result
        assert "Scope Restraint" in result

    def test_includes_oca_standards(self):
        result = compose_guidelines()
        assert "Odoo Community Association (OCA) Standards" in result
        assert "ir.model.access.csv" in result

    def test_version_specific_addenda(self):
        for ver in ["14.0", "15.0", "16.0", "17.0", "18.0", "19.0", "20.0"]:
            result = compose_guidelines(version=ver)
            major = ver.split(".")[0]
            assert f"Odoo {major}" in result


class TestComposeGuidelinesIndex:
    def test_index_is_much_smaller_than_full(self):
        index = compose_guidelines_index("18.0")
        full = compose_guidelines("18.0")
        assert len(index) < len(full) / 3

    def test_index_contains_titles(self):
        index = compose_guidelines_index()
        assert "# Odoo Boost Guidelines Index" in index
        assert "odoo://guidelines/oca" in index

    def test_index_mentions_version(self):
        assert "Odoo 18.0" in compose_guidelines_index("18.0")


def test_generated_agent_guidelines_route_to_full_expert_content(tmp_path):
    reference_dir = ".agents/skills/guidelines"
    content = compose_agent_guidelines("18.0", reference_dir)
    created = install_guideline_references(tmp_path / reference_dir, "18.0")

    assert "First-pass coding (default)" in content
    assert "## Medium effort" in content
    assert "## High effort" in content
    assert "configured Odoo version" in content
    assert "Every task starts" in content
    assert "native file reads" in content
    assert "list_view_tag: list" in content
    assert len(content) < len(compose_guidelines("18.0")) / 3
    assert compose_guidelines("18.0").strip() not in content
    for filename in _CORE_FILES:
        assert (tmp_path / reference_dir / filename).is_file()
    assert f"{reference_dir}/security.md" in content
    assert f"{reference_dir}/versions/v18.md" in content
    assert all(path.is_file() for path in created)
    assert len(created) == len(_CORE_FILES) + 1
