"""Assembles guidelines from markdown parts into a single document."""

from __future__ import annotations

import importlib.resources
from pathlib import Path

from odoo_boost.versions import get_version_profile, version_guidance

_CORE_FILES = [
    "operating_rules.md",
    "odoo_general.md",
    "module_structure.md",
    "orm_best_practices.md",
    "security.md",
    "views_and_ui.md",
    "controllers.md",
    "javascript_owl.md",
    "testing.md",
    "coding_style.md",
    "oca_standards.md",
]


def _read_resource(subpath: str) -> str:
    """Read a markdown file from the guidelines/core package data."""
    ref = importlib.resources.files("odoo_boost.guidelines") / "core" / subpath
    return ref.read_text(encoding="utf-8")


def _version_file(version: str | None) -> str | None:
    profile = get_version_profile(version)
    return profile.guideline_file if profile else None


def compose_agent_guidelines(version: str | None, reference_dir: str) -> str:
    """Full expert guidelines, with a supplementary index for targeted references."""
    lines = [
        compose_guidelines(version).rstrip(),
        "",
        "## Reference files and skills",
        "",
        "The expert guidelines above are included in full. Topic copies are available below.",
        "Paths below are relative to the project root.",
        f"Skill catalog: `{Path(reference_dir).parent.as_posix()}/SKILLS_ROUTING.md`.",
        "Load specialized skills when relevant to the task.",
        "",
    ]
    for filename in _CORE_FILES:
        if filename == "operating_rules.md":
            continue
        title = next(
            (
                line.lstrip("# ").strip()
                for line in _read_resource(filename).splitlines()
                if line.startswith("#")
            ),
            filename.removesuffix(".md"),
        )
        lines.append(f"- {title}: `{reference_dir}/{filename}`")
    version_file = _version_file(version)
    if version_file:
        lines.append(f"- Odoo {version} version notes: `{reference_dir}/{version_file}`")
    return "\n".join(lines) + "\n"


def install_guideline_references(target_dir: Path, version: str | None) -> list[Path]:
    """Write topic files used by the compact generated agent instructions."""
    filenames = list(_CORE_FILES)
    version_file = _version_file(version)
    if version_file:
        filenames.append(version_file)
    created = []
    for filename in filenames:
        path = target_dir / filename
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(_read_resource(filename), encoding="utf-8")
        created.append(path)
    return created


def compose_guidelines_index(version: str | None = None) -> str:
    """Return a compact index (titles and top headings) of the guidelines.

    Useful when an agent wants an overview without loading the full text.
    """
    lines = [
        "# Odoo Boost Guidelines Index",
        "",
        "Use the generated agent instructions to find local topic references.",
        "The `odoo://guidelines/oca` resource contains the full reference when needed.",
        version_guidance(version),
        "",
    ]

    for filename in _CORE_FILES:
        content = _read_resource(filename)
        title = ""
        headings: list[str] = []
        for line in content.splitlines():
            if line.startswith("# "):
                title = line[2:].strip()
            elif line.startswith("## ") and len(headings) < 8:
                headings.append(line[3:].strip())
        if title:
            lines.append(f"## {title}")
            lines.extend(f"- {heading}" for heading in headings)
            lines.append("")

    if version:
        lines.append(f"Version-specific notes: Odoo {version}")
        lines.append("")

    return "\n".join(lines)


def compose_guidelines(version: str | None = None) -> str:
    """Assemble all core guideline files plus a version-specific addendum.

    Args:
        version: Odoo version string (e.g. '17.0', '18.0', '19.0').
                 If None, no version-specific section is appended.

    Returns:
        A single markdown string with all guidelines concatenated.
    """
    parts: list[str] = []

    parts.append("# Odoo Development Guidelines\n")
    parts.append(
        "> Auto-generated by **Odoo Boost**. "
        "These guidelines help AI coding agents write idiomatic Odoo code.\n"
    )

    for filename in _CORE_FILES:
        content = _read_resource(filename)
        parts.append(content.strip())
        parts.append("")  # blank line separator

    parts.append(version_guidance(version))

    # Version-specific addendum
    version_file = _version_file(version)
    if version_file:
        parts.append(_read_resource(version_file).strip())
        parts.append("")

    return "\n\n".join(parts) + "\n"
