"""Assembles guidelines from markdown parts into a single document."""

from __future__ import annotations

import importlib.resources

from packaging.version import InvalidVersion, Version
from packaging.version import parse as parse_version

_CORE_FILES = [
    "operating_rules.md",
    "odoo_general.md",
    "module_structure.md",
    "orm_best_practices.md",
    "security.md",
    "views_and_ui.md",
    "controllers.md",
    "javascript_owl.md",
    "testing.md",
    "coding_style.md",
    "oca_standards.md",
]


def _read_resource(subpath: str) -> str:
    """Read a markdown file from the guidelines/core package data."""
    ref = importlib.resources.files("odoo_boost.guidelines") / "core" / subpath
    return ref.read_text(encoding="utf-8")


def compose_guidelines_index(version: str | None = None) -> str:
    """Return a compact index (titles and top headings) of the guidelines.

    Useful when an agent wants an overview without loading the full text.
    """
    lines = [
        "# Odoo Boost Guidelines Index",
        "",
        "Compact index. Load the full guidelines from the `odoo://guidelines/oca`",
        "resource or the generated `AGENTS.md`.",
        "",
    ]

    for filename in _CORE_FILES:
        content = _read_resource(filename)
        title = ""
        headings: list[str] = []
        for line in content.splitlines():
            if line.startswith("# "):
                title = line[2:].strip()
            elif line.startswith("## ") and len(headings) < 8:
                headings.append(line[3:].strip())
        if title:
            lines.append(f"## {title}")
            lines.extend(f"- {heading}" for heading in headings)
            lines.append("")

    if version:
        lines.append(f"Version-specific notes: Odoo {version}")
        lines.append("")

    return "\n".join(lines)


def compose_guidelines(version: str | None = None) -> str:
    """Assemble all core guideline files plus a version-specific addendum.

    Args:
        version: Odoo version string (e.g. '17.0', '18.0', '19.0').
                 If None, no version-specific section is appended.

    Returns:
        A single markdown string with all guidelines concatenated.
    """
    parts: list[str] = []

    parts.append("# Odoo Development Guidelines\n")
    parts.append(
        "> Auto-generated by **Odoo Boost**. "
        "These guidelines help AI coding agents write idiomatic Odoo code.\n"
    )

    for filename in _CORE_FILES:
        content = _read_resource(filename)
        parts.append(content.strip())
        parts.append("")  # blank line separator

    # Version-specific addendum
    if version:
        try:
            parsed = parse_version(str(version))
            major = str(parsed.major) if isinstance(parsed, Version) else str(version).split(".")[0]
        except (InvalidVersion, TypeError):
            major = str(version).split(".")[0]

        version_file = f"versions/v{major}.md"
        try:
            version_content = _read_resource(version_file)
            parts.append(version_content.strip())
            parts.append("")
        except (FileNotFoundError, TypeError):
            pass  # No version-specific guidelines available

    return "\n\n".join(parts) + "\n"
